template_path: CloudtrailLogAggregation.yaml
stack_name: CloudtrailLogAggregation
parameters:
  AdmincentralAwsAccountId: !ssm /infra/AdmincentralAwsAccountId
  BridgeDevAwsAccountId: !ssm /infra/BridgeDevAwsAccountId
  BridgeProdAwsAccountId: !ssm /infra/BridgeProdAwsAccountId
  ScicompAwsAccountId: !ssm /infra/ScicompAwsAccountId
  SynapseProdAwsAccountId: !ssm /infra/SynapseProdAwsAccountId
  SynapseDevAwsAccountId: !ssm /infra/SynapseDevAwsAccountId
  SynapseDwAwsAccountId: !ssm /infra/SynapseDwAwsAccountId
  SageItAwsAccountId: !ssm /infra/SageItAwsAccountId
  OrganizationsAwsAccountId: !ssm /infra/OrganizationsAwsAccountId
  SandboxAwsAccountId: !ssm /infra/SandboxAwsAccountId
  SecuritycentralAwsAccountId: !ssm /infra/SecuritycentralAwsAccountId
